apiVersion: v1
kind: Pod
metadata:
  name: ui-pod
  labels:
    name: ui-pod
spec:
  containers:
  - name: ubuntu
    image: mendeza/mistral-llm-rag-ui:0.0.7
    command: ["/bin/sh", "-c"]
    args:
      - echo starting;
        export API_HOST={{API_HOST}};
        export API_PORT={{API_PORT}};
        export DB_PATH={{DB_PATH}};
        python3 -m chainlit run {{APP_PY_PATH}} --host 0.0.0.0 --port {{UI_PORT}}
    ports:
    - containerPort: {{UI_PORT}}
      hostPort: {{UI_PORT}}
    volumeMounts:
    - name: host-volume
      mountPath: /nvmefs1/
    - name: embed-cache
      mountPath: /root/.cache
  volumes:
  - name: host-volume
    hostPath:
      path: {{HOST_VOLUME}}
  - name: embed-cache
    hostPath:
      path: {{EMBED_CACHE}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui-pod-svc
  name: ui-pod-svc
spec:
  type: LoadBalancer
  ports:
  - nodePort: 31173
    port: {{UI_PORT}}
    protocol: TCP
    targetPort: {{UI_PORT}}
  selector:
    name: ui-pod
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: {{UI_IP}}
